# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(101215)
$foreground = rgb(C0D6ED)
$color0 = rgb(383A3D)
$color1 = rgb(030E19)
$color2 = rgb(061421)
$color3 = rgb(214161)
$color4 = rgb(153D7D)
$color5 = rgb(396899)
$color6 = rgb(396899)
$color7 = rgb(9DBDDD)
$color8 = rgb(6E849B)
$color9 = rgb(041321)
$color10 = rgb(081B2C)
$color11 = rgb(2D5681)
$color12 = rgb(1C51A7)
$color13 = rgb(4C8BCC)
$color14 = rgb(4C8BCC)
$color15 = rgb(9DBDDD)
