# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #C0D6ED
background         #101215
cursor             #64788C

active_tab_foreground     #101215
active_tab_background     #C0D6ED
inactive_tab_foreground   #C0D6ED
inactive_tab_background   #101215

active_border_color   #C0D6ED
inactive_border_color #101215
bell_border_color     #030E19

color0      #383A3D
color1		#030E19
color2		#061421
color3		#214161
color4		#153D7D
color5		#396899
color6		#396899
color7		#9DBDDD
color8		#6E849B
color9		#041321
color10		#081B2C
color11		#2D5681
color12		#1C51A7
color13		#4C8BCC
color14		#4C8BCC
color15		#9DBDDD
